// Character data
        const consonants = [
            { roman: 'ka', devanagari: 'क' },
            { roman: 'kha', devanagari: 'ख' },
            { roman: 'ga', devanagari: 'ग' },
            { roman: 'gha', devanagari: 'घ' },
            { roman: 'ṅa', devanagari: 'ङ' },
            { roman: 'ca', devanagari: 'च' },
            { roman: 'cha', devanagari: 'छ' },
            { roman: 'ja', devanagari: 'ज' },
            { roman: 'jha', devanagari: 'झ' },
            { roman: 'ña', devanagari: 'ञ' },
            { roman: 'ṭa', devanagari: 'ट' },
            { roman: 'ṭha', devanagari: 'ठ' },
            { roman: 'ḍa', devanagari: 'ड' },
            { roman: 'ḍha', devanagari: 'ढ' },
            { roman: 'ṇa', devanagari: 'ण' },
            { roman: 'ta', devanagari: 'त' },
            { roman: 'tha', devanagari: 'थ' },
            { roman: 'da', devanagari: 'द' },
            { roman: 'dha', devanagari: 'ध' },
            { roman: 'na', devanagari: 'न' },
            { roman: 'pa', devanagari: 'प' },
            { roman: 'pha', devanagari: 'फ' },
            { roman: 'ba', devanagari: 'ब' },
            { roman: 'bha', devanagari: 'भ' },
            { roman: 'ma', devanagari: 'म' },
            { roman: 'ya', devanagari: 'य' },
            { roman: 'ra', devanagari: 'र' },
            { roman: 'la', devanagari: 'ल' },
            { roman: 'ḷa', devanagari: 'ळ' },
            { roman: 'va', devanagari: 'व' },
            { roman: 'śa', devanagari: 'श' },
            { roman: 'ṣa', devanagari: 'ष' },
            { roman: 'sa', devanagari: 'स' },
            { roman: 'ha', devanagari: 'ह' },
            { roman: 'kṣa', devanagari: 'क्ष' },
            { roman: 'jña', devanagari: 'ज्ञ' },
            { roman: 'tra', devanagari: 'त्र' },
            { roman: 'dya', devanagari: 'द्या' },
            { roman: 'śra', devanagari: 'श्र' }
        ];

        const vowels = [
            { roman: 'a', devanagari: 'अ', matra: null },
            { roman: 'ā', devanagari: 'आ', matra: 'ा' },
            { roman: 'i', devanagari: 'इ', matra: 'ि' },
            { roman: 'ī', devanagari: 'ई', matra: 'ी' },
            { roman: 'u', devanagari: 'उ', matra: 'ु' },
            { roman: 'ū', devanagari: 'ऊ', matra: 'ू' },
            { roman: 'ṛ', devanagari: 'ऋ', matra: 'ृ' },
            { roman: 'ṝ', devanagari: 'ॠ', matra: 'ॄ' },
            { roman: 'ḷ', devanagari: 'ऌ', matra: 'ॢ' },
            { roman: 'ḹ', devanagari: 'ॡ', matra: 'ॣ' },
            { roman: 'e', devanagari: 'ए', matra: 'े' },
            { roman: 'ai', devanagari: 'ऐ', matra: 'ै' },
            { roman: 'o', devanagari: 'ओ', matra: 'ो' },
            { roman: 'au', devanagari: 'औ', matra: 'ौ' },
            { roman: 'visarga', devanagari: 'ः', matra: null },
            { roman: 'virama', devanagari: '्', matra: null },
            { roman: 'anusvara', devanagari: 'ं', matra :null },
            { roman: 'candrabindu', devanagari: 'ँ', matra: null },
            { roman: 'avagraha', devanagari: 'ऽ', matra: null},
        ];

        const specialChars = [
            { roman: '॑', devanagari: '॑', title: 'svarita' },
            { roman: '॒', devanagari: '॒', title: 'udātta' },
            { roman: '॓', devanagari: '॓', title: 'anudātta' },
            { roman: '॔', devanagari: '॔', title: 'visarga' },
            { roman: 'ॕ', devanagari: 'ॕ', title: 'avagraha' },
            { roman: 'ॖ', devanagari: 'ॖ', title: 'anusvāra' },
            { roman: 'ॗ', devanagari: 'ॗ', title: 'candrabindu' },
            { roman: '़', devanagari: '़', title: 'nukta' },
            { roman: '।', devanagari: '।', title: 'danda' },
            { roman: '॥', devanagari: '॥', title: 'double danda' },
            { roman: '॰', devanagari: '॰', title: 'abbreviation sign' },
            { roman: 'ॐ', devanagari: 'ॐ', title: 'om' }
        ];

        const vedicDiacritics = [
            { title: 'udatta', char: '\u0951' },
            { title: 'anudatta', char: '\u0952' },
            { title: 'grave accent', char: '\u0953' },
            { title: 'acute accent', char: '\u0954' },
            { title: 'nihshvasa', char: '\u1CD3' },
            { title: 'yajurvedic midline svarita', char: '\u1CD4' },
            { title: 'yajurvedic aggravated independent svarita', char: '\u1CD5' },
            { title: 'yajurvedic independent svarita', char: '\u1CD6' },
            { title: 'yajurvedic kathaka independent svarita', char: '\u1CD7' },
            { title: 'candra below', char: '\u1CD8' },
            { title: 'yajurvedic kathaka independent svarita schroeder', char: '\u1CD9' },
            { title: 'double svarita', char: '\u1CDA' },
            { title: 'triple svarita', char: '\u1CDB' },
            { title: 'kathaka anudatta', char: '\u1CDC' },
            { title: 'dot below', char: '\u1CDD' },
            { title: 'two dots below', char: '\u1CDE' },
            { title: 'three dots below', char: '\u1CDF' },
            { title: 'rigvedic kashmiri independent svarita', char: '\u1CE0' },
            { title: 'atharvavedic independent svarita', char: '\u1CE1' },
            { title: 'visarga svarita', char: '\u1CE2' },
            { title: 'visarga udatta', char: '\u1CE3' },
            { title: 'reversed visarga udatta', char: '\u1CE4' },
            { title: 'visarga anudatta', char: '\u1CE5' },
            { title: 'reversed visarga anudatta', char: '\u1CE6' },
            { title: 'visarga udatta with tail', char: '\u1CE7' },
            { title: 'visarga anudatta with tail', char: '\u1CE8' },
            { title: 'anusvara antargomukha', char: '\u1CE9' },
            { title: 'anusvara bahirgomukha', char: '\u1CEA' },
            { title: 'anusvara vamagomukha', char: '\u1CEB' },
            { title: 'anusvara vamagomukha with tail', char: '\u1CEC' },
            { title: 'hexiform long anusvara', char: '\u1CEE' },
            { title: 'long anusvara', char: '\u1CEF' },
            { title: 'rthang long anusvara', char: '\u1CF0' },
            { title: 'anusvara ubhayato mukha', char: '\u1CF1' },
            { title: 'ardhavisarga', char: '\u1CF2' },
            { title: 'rotated ardhavisarga', char: '\u1CF3' },
            { title: 'candra above', char: '\u1CF4' },
        ];
        // SAMA_svara array with descriptive titles for superscript numbers
        const SAMA_svara = [
            { title: 'karshana (SV)', char: '\u1CD0' },
            { title: 'shara (SV)', char: '\u1CD1' },
            { title: 'prenkha (SV)', char: '\u1CD2' },
            { title: 'combining a (SV)', char: '\uA8EA' },
            { title: 'combining u (SV)', char: '\uA8EB' },
            { title: 'combining ka (SV)', char: '\uA8EC' },
            { title: 'combining na (SV)', char: '\uA8ED' },
            { title: 'combining pa (SV)', char: '\uA8EE' },
            { title: 'combining ra (SV)', char: '\uA8EF' },
            { title: 'combining vi (SV)', char: '\uA8F0' },
            { title: 'combining avagraha (SV)', char: '\uA8F1' },
            { title: 'combining chandrabindu (SV)', char: '\uA8F2' },
            { title: 'independent chandrabindu (SV)', char: '\uA8F3' },
            { title: 'independent anusvara (SV)', char: '\uA8F4' },
            // Superscript numerals
            { title: 'superscript 0', char: '\uA8E0' },
            { title: 'superscript 1', char: '\uA8E1' },
            { title: 'superscript 2', char: '\uA8E2' },
            { title: 'superscript 3', char: '\uA8E3' },
            { title: 'superscript 4', char: '\uA8E4' },
            { title: 'superscript 5', char: '\uA8E5' },
            { title: 'superscript 6', char: '\uA8E6' },
            { title: 'superscript 7', char: '\uA8E7' },
            { title: 'superscript 8', char: '\uA8E8' },
            { title: 'superscript 9', char: '\uA8E9' }
        ];
        // Devanagari digits 0-9
        const numbers = [
            { roman: '0', devanagari: '०' },
            { roman: '1', devanagari: '१' },
            { roman: '2', devanagari: '२' },
            { roman: '3', devanagari: '३' },
            { roman: '4', devanagari: '४' },
            { roman: '5', devanagari: '५' },
            { roman: '6', devanagari: '६' },
            { roman: '7', devanagari: '७' },
            { roman: '8', devanagari: '८' },
            { roman: '9', devanagari: '९' }
        ];

